import { SessionProvider } from "next-auth/react";
import { GeistSans } from "geist/font/sans";
import { Metadata } from "next";
import { auth } from "~/server/auth";
import "~/styles/globals.css";
import { TooltipProvider } from "@radix-ui/react-tooltip";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await auth();

  return (
    <SessionProvider session={session}>
      <TooltipProvider delayDuration={100}>

      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="bg-gray-900 text-gray-100">
          {children}
        </body>
      </html>
      </TooltipProvider>
    </SessionProvider>
  );
}
